PROGRAM RUNTIME

INTEGER TID, OMP_GET_THREAD_NUM

!$OMP PARALLEL PRIVATE(TID) NUM_THREADS(3)
      TID = OMP_GET_THREAD_NUM()

!$OMP DO SCHEDULE(RUNTIME)
      DO I=1, 10
         PRINT*, 'Runtime Thread ',TID, 'is running number ',I
      ENDDO

!$OMP END PARALLEL

END
