PROGRAM TASK

INTEGER TID, OMP_GET_THREAD_NUM

!$OMP PARALLEL PRIVATE(TID, NS)
      TID = OMP_GET_THREAD_NUM()
!$OMP SINGLE
      DO I=1, 9
         IF(I <= 9) NS=3
         IF(I <= 6) NS=2
         IF(I <= 3) NS=1
!$OMP TASK UNTIED
         PRINT*, I,'th SLEEP ', NS ,' SEC', ' TID =', OMP_GET_THREAD_NUM()
         CALL SLEEP(NS)
!$OMP END TASK
      ENDDO
!$OMP END SINGLE
!$OMP END PARALLEL

ENDPROGRAM
